import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import JSZip from 'jszip';
import { appConfig } from '@/lib/config';
import * as fs from 'fs';
import * as path from 'path';

export async function GET(req: NextRequest) {
  const session = await getServerSession(authOptions);
  if (!session?.user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const zip = new JSZip();

  // Add config
  zip.file('config/app.config.json', JSON.stringify(appConfig, null, 2));

  // Add generated schema
  const schemaPath = path.join(process.cwd(), 'prisma', 'schema.prisma');
  if (fs.existsSync(schemaPath)) {
    zip.file('prisma/schema.prisma', fs.readFileSync(schemaPath, 'utf-8'));
  }

  // Add package.json
  zip.file('package.json', JSON.stringify({
    name: appConfig.app.name.toLowerCase().replace(/\s+/g, '-'),
    version: '1.0.0',
    private: true,
    scripts: {
      predev: 'npx ts-node --project tsconfig.scripts.json scripts/generate-schema.ts',
      dev: 'next dev',
      prebuild: 'npx ts-node --project tsconfig.scripts.json scripts/generate-schema.ts',
      build: 'next build',
      start: 'next start',
    },
    dependencies: {
      '@next-auth/prisma-adapter': '^1.0.7',
      '@prisma/client': '^5.10.2',
      'bcryptjs': '^2.4.3',
      'jszip': '^3.10.1',
      'next': '14.1.0',
      'next-auth': '^4.24.7',
      'next-intl': '^3.9.1',
      'papaparse': '^5.4.1',
      'react': '^18',
      'react-dom': '^18',
      'recharts': '^2.12.2',
      'zod': '^3.22.4',
    },
  }, null, 2));

  // Add README
  zip.file('README.md', `# ${appConfig.app.name}

Generated by AppForge — Config-Driven Application Platform.

## Setup

1. \`npm install\`
2. Set up \`.env\` with \`DATABASE_URL\` and \`NEXTAUTH_SECRET\`
3. \`npm run dev\`

## Configuration

Edit \`config/app.config.json\` to modify entities, pages, and settings.

## Entities

${appConfig.entities.map((e) => `- **${e.name}**: ${e.fields.map((f) => f.name).join(', ')}`).join('\n')}

## Pages

${appConfig.pages.map((p) => `- \`${p.route}\` — ${p.type} (${p.title})`).join('\n')}
`);

  // Add .env.example
  zip.file('.env.example', `DATABASE_URL="postgresql://user:password@localhost:5432/mydb"
NEXTAUTH_SECRET="your-secret-here"
NEXTAUTH_URL="http://localhost:3000"
GOOGLE_CLIENT_ID="your-google-client-id"
GOOGLE_CLIENT_SECRET="your-google-client-secret"
`);

    const buffer = await zip.generateAsync({ type: 'nodebuffer' });

  return new NextResponse(new Uint8Array(buffer), {
    headers: {
      'Content-Type': 'application/zip',
      'Content-Disposition': `attachment; filename="${appConfig.app.name.replace(/\s+/g, '-')}-export.zip"`,
    },
  });
}
